### ISSUE TITLE
draft projects should not be accessible to any user

### ISSUE THREAD

**Issue by pgiraud** [hotosm/osm-tasking-manager2#405]

**Comment by ethan-nelson** [comment]
I can work on this soon unless it's been already fixed (though no pull request ever mentioned it).

**Comment by bgirardot** [comment]
This is not fixed. I think it make sense to let project mangers/admins see all the draft projects but probably not regular mappers.

**Comment by ethan-nelson** [comment]
@bgirardot digging a little deeper, I could use some clarification. Is it that we want the draft projects to show up in the list of projects for all project managers and admins, but right now it's only showing up for the respective authors? I thought this issue was an access restriction to the actual project, but that doesn't seem to be the case since I as just a user can see http://tasks.hotosm.org/project/1067.

**Comment by ethan-nelson** [comment]
Nevermind, I'm understanding the ticket now :)

**Comment by d3netxer** [comment]
hmm I would like to share a draft of a project with co-organizers who are not admins. I think I will need to publish the project and make it low-priority. I'm assuming I can switch it back into draft mode after it is reviewed remotely.

**Comment by bgirardot** [comment]
@d3netxer Another option is to make it a private project and just add them for access then remove the private part when you want it to go live.

**Comment by pgiraud** [comment]
What about creating a project on the hot dev instance?

Envoyé de mon iPhone

**Comment by d3netxer** [comment]
ok thanks, both good suggestions

**Comment by ethan-nelson** [comment]
This has been fixed with #629 and #765.
