### ISSUE TITLE
Error accessing random task

### ISSUE THREAD

**Issue by pierzen** [hotosm/osm-tasking-manager2#564]
Both in Chrome and Firefox, selecting a random task returns the message 
Error: random task should have returned a task ID but did not

Was reported through Twitter. I have the same problem.
This with http://tasks.hotosm.org/project/943

Working with http://tasks.hotosm.org/project/945

**Comment by pgiraud** [comment]
This is probably due to the fact that everything was already done. Can you confirm?

**Comment by pierzen** [comment]
You are right.  This task was completed and we wanted the contributors to pass a second run, validating the tasks.  In such cases, we should give instruction to select a square.

**Comment by pierzen** [comment]
I had closed the comment, but realize that this problem should be corrected with the appropriate message that indicates that no other task to complete.

**Comment by Nick-Tallguy** [comment]
Hi, someone I have been training had the same problem a short while ago whilst working on http://tasks.hotosm.org/project/868.  I had a quick look and there were 4 squares which had been invalidated and needed attention, but otherwise the project was complete. Following my instructions she selected a square by clicking on it on the map, and she was then able to carry on and map in the normal way.

**Comment by aawiseman** [comment]
Another person said the same thing -- maybe it should say "all tasks are done" https://twitter.com/danielpunkass/status/595666696003813376

**Comment by pgiraud** [comment]
Fixed via #603.
