### ISSUE TITLE
Feature: Invalidate all tasks

### ISSUE THREAD

**Issue by planemad** [hotosm/osm-tasking-manager2#690]
While working on projects with a large number of tasks like the [Kyushu road realignment](http://tasks.openstreetmap.in/project/57), there is a need to mass invalidate tasks if the mapping instructions have been updated to include some more features.

This is very useful for a project manager to bypass the usual workflow of selecting every task and manually invalidating each task with a comment which can become tedious. Since the only other option now is to abandon the project and create a new one, a feature like this can save valuable time in emergency situations.

This is a power feature visible only for the project admins and can be placed in the Project edit > Misc section. It should allow admins to invalidate all tasks marked as done with a comment using a single click.

**Comment by pgiraud** [comment]
Thanks for the detailed explanation. This looks like a interesting and decent addition indeed.

**Comment by batpad** [comment]
I started to work on this on a branch: https://github.com/osm-in/osm-tasking-manager2/tree/invalidate-all . 

Creates an end-point `/project/{project_id}/invalidate_all` that accepts a POST param of 'comments' and invalidates all "done" tasks for that project. Contains [tests](https://github.com/osm-in/osm-tasking-manager2/blob/533accb7063b4220868665c4ee4742552fe86411/osmtm/tests/test_project.py#L732).

I'm just unsure of where this should go on the front-end. In this branch, I've just tacked it in the `task.empty.mako` template, but that's obviously awkward.

I also find putting it inside Project Edit to be awkward since the rest of that page is a single form with a save button and it's a bit strange to have a form within there that performs a separate action.

@pgiraud please do let me know if I can make any changes to the back-end code / if you feel this implementation is okay or if it should be done differently.

Once we figure out a place for it in the UI, and if the code looks okay, I can make a PR.

**Comment by planemad** [comment]
@batpad there are two possible locations to place such a feature:

- At the bottom of `Edit Project > Instructions`: Such a feature is likely to be used when project instructions were updated midway and requires redo. So it makes sense to have this here probably as a checkbox and text input for the invalidate comment.
- At the bottom of `Project Stats tab`: This makes sense if we look at the invalidation as a stats reset feature.

Considering this is a pretty powerful feature, i'm leaning towards hiding it in the project settings page.

**Comment by ethan-nelson** [comment]
I would agree to put it somewhere in the edit project screen.

**Comment by pgiraud** [comment]
We could imagine a button in the editing interface which opens a modal window with a form for the tasks invalidation. The form could be sent with an AJAX request without reloading the page. Well this is relevant if put in the project main page as well.

I also would like the invalidation to be safe. I want to prevent mishandling. What I mean is that the user would for example have to for example write a simple text in an input field. This would make the invalidation more difficult than simply pushing a button (by accident).

**Comment by batpad** [comment]
+1 for the modal and AJAX. Will spend a little bit of time figuring out the cleanest way to do this, also so its easy to add this functionality in other places if required.

Wrt to the safety of the operation, the current implementation I have requires a comment to be input by the user. Do you think this is enough, or should we have an additional text box where we ask the user to enter some simple word?

Should have something by early next week.

**Comment by pierzen** [comment]
Such invalidation should be restricted to the creator of the Job.  We had experience in the pas where people took initiatives to delete jobs without asking first.

**Comment by batpad** [comment]
Made some progress on implementing this via a modal.

Some screenshots:

Button on Project Edit page (currently put under Misc, but could be moved):

![screenshot 2015-10-26 14 45 38](https://cloud.githubusercontent.com/assets/72280/10725241/859a7742-7bf0-11e5-8cc6-db80759b3597.png)

Modal dialog that opens:

![screenshot 2015-10-26 14 45 52](https://cloud.githubusercontent.com/assets/72280/10725245/9c8ae1c6-7bf0-11e5-8675-4bf58178630b.png)

This all seems to work in the branch I'm working out of: https://github.com/osm-in/osm-tasking-manager2/tree/invalidate-all . Would love to get some feedback, or if this seems generally agreeable, I will clean up the CSS and code a bit and make a Pull Request to take this forward.

Thank you!

**Comment by pgiraud** [comment]
Hi @batpad 
Here are some comments about your implementation.

For the interface first, I think that it's a good option to put this feature in the misc tab in the project editing page. However, I would a small title "task invalidation" label just before the button, so that it's visually separated.
Also, I think that the button is a bit large.
Finally, I would add the text as a help message.
See f5d875f88db47411617a068c5a9946efda248a55.

About the functionality, I think that we really need to prevent project managers to do an invalidation by accident as much as possible. For that, I think that it would be a good idea to have the project managers prove that they know what they're doing, ie. that they read the text before clicking the button. Adding a comment is in my opinion a bit too easy. I like the github's method which consists in having the user write something specifically. In our case, having them write the number of the project would be enough I think.
So my idea is adding a simple field (not a textarea) with a text like the following:
"To make sure that you know what you're doing, please write the number of the current project in the following field".
The project number would then be compared server-side when submitting the form.
Ideally, the "invalidate all done tasks" would be disabled until the project number is typed in. But this may require too much work.

**Comment by batpad** [comment]
@pgiraud thanks much for the feedback - all sounds great.

Will work on implementing these by early next week and update here.

I may need some help getting all the translation / Transifex stuff done right - perhaps after this is done, if I have problems with that, I can ask for help?

Thanks again! :)

**Comment by pgiraud** [comment]
I don't think you need to pay much attention with the transifex stuff. In general, as soon as you use the correct syntax for translations in the code, the messages will be automatically be extracted, and with the support from @dodobas, we'll do the required actions to have the string to be translated transmitted to transifex.

You need to use "${_('the string')}" in the templates.
See https://github.com/hotosm/osm-tasking-manager2/commit/f5d875f88db47411617a068c5a9946efda248a55#diff-62881a4b069a4e863c4cd687ca75a675R438

**Comment by batpad** [comment]
Thanks @pgiraud 

Have pushed code to my branch implementing the template changes as you suggested, translatable strings and the feature to require user to enter the project id in an input field.

Commits are here: https://github.com/osm-in/osm-tasking-manager2/commits/invalidate-all

It probably needs a bit of minor CSS changes before I line up a Pull Request. Does everything else look okay? Can I go ahead?

**Comment by pgiraud** [comment]
Excellent.
Yes please go ahead.

**Comment by pgiraud** [comment]
I just figured out why the close button is not correctly rendered in the modal.
The following line should be uncommented:
https://github.com/hotosm/osm-tasking-manager2/blob/master/osmtm/static/css/bootstrap.less#L38

This should be done more generally and is not directly related to your work.

**Comment by batpad** [comment]
Ah, I was wondering about that :-) - was going to look at it along with other minor CSS things.  Shall I make this change in my branch and see how it looks and make it a part of the pull request or would you rather do this separately?

Will do some minor CSS fixes for validation errors and such and make the pull request tomorrow. Thanks!

**Comment by batpad** [comment]
Have made a Pull Request for this. @pgiraud do let me know if there are changes I can make to improve this. Thanks.

**Comment by pierzen** [comment]
Is this command access restricted to the owner of the job?

**Comment by batpad** [comment]
It currently checks if the user has permission to edit the project. (i.e. the "project_edit" permission) - which I assume is for project owners and admins?

Is there a more restrictive permission you would prefer?

**Comment by pierzen** [comment]
Unless this has been changed recently, anyone can edit others projects. Looking at the Edit panel, I only see that we can create a private job with a list of users that can access it.
But I dont see any feature to authorize others to edit.

I insist on this because we already had the experience in the past that somebody decided to delete a job without discussing with the Coordinator of the Activation or the creator of the job.  To Invalidate all tasks without consulting could also be quite damaging in the context of an Activation.

**Comment by batpad** [comment]
@pierzen sorry, this might be my misunderstanding of how project admins are assigned. I would absolutely agree with you if anyone can edit other projects, they should not be able to access this feature.

@pgiraud could you clarify what users have the "project_edit" permission? My understanding is that these are site admins, the project owner, and people who have been explicitly granted permission to edit the project by a site admin or project owner. And once a person has a "project_edit" permission, they can do things like archive the project, etc. - my understanding was that if a person can archive a project, change instructions, etc. they should also be able to access this feature.

I apologize if I misunderstood this, and I absolutely agree with @pierzen that we should be careful about who has access to this. @pgiraud could you take a call on this, and if the current "project_edit" permission check is not appropriate, let me know what might be a more sensible permission check to make? Am happy to make the required changes and push code. Thanks!

**Comment by maning** [comment]
> I insist on this because we already had the experience in the past that somebody decided to delete a job 

@pierzen, I'm not aware that project managers or admins can actually delete a project.  Maybe archive/unpublish?  PMs can of course edit project details. Unless we implement finegrained permissions, I think invalidation is within the confines of what PMs can do. 

> Is this command access restricted to the owner of the job?

In the context of activation coordination, I don't think we should restrict to project owners.  Oftentimes, big activations require several activators to manage TM projects.  Restricting to project owners will result to very high bus factor.

**Comment by pgiraud** [comment]
Hi @maning.
You are right. There's no way anyone can delete a project. Project managers can only archive/unpublish a project. This feature has been added as a workaround to prevent project managers to delete a project by accident.

> In the context of activation coordination, I don't think we should restrict to project owners. Oftentimes, big activations require several activators to manage TM projects. Restricting to project owners will result to very high bus factor.

I fully agree with this statement.
Ideally the tool should let the project owner define the project managers who can edit the project. But this feature is not going to be added soon.

For now, I think that we should let anyone with "project_edit" permission (ie. the project manager and administrators) to invalidate all tasks for a project. And since the invalidation requires more than simply pushing a button, I don't think it will be done by accident.
Project managers usually don't do nasty things (like vandalism) with project editing. I don't see any reason why they would for invalidation.

**Comment by pierzen** [comment]
@maning We had this problem of deleting jobs with one of the first activation done through the tasking manager. And this was done by an experienced editor who simply disagreed to have two jobs for the same area, each with specific instructions. This was the Samoa Cyclone Simulation. I had discussion about this at the time with @pgiraud. The solution was to remove the delete option.

**Comment by pgiraud** [comment]
This has been fixed in #696. Closing.
