### ISSUE TITLE
js libraries updates/overlaps

### ISSUE THREAD

**Issue by hyances** [hotosm/osm-tasking-manager2#750]
Hello!

I just update to last version and now dealing with two js libraries issues:

1) osm-tasking-manager2/osmtm/static/js/lib/showdown/ is pulling as empty folder (after a git submodule update);

2) there is a jquery versions overlap between mako and bootstrap.  Mako bring with 1.7 and bootstrap comes with 1.9.1.

Thanks!

**Comment by hyances** [comment]
I was pulling from master branch; not from current stable 2.12.

**Comment by pgiraud** [comment]
Still, this is weird. master and 2.12 don't have any significant differences.

**Comment by KaiDalgleish** [comment]
I'm a new contributor trying to get set up, and having a similar issue. 
- I started on the master branch (it wasn't clear to me that I should be on 2.12) and got an error because showdown.js was in the wrong directory. showdown/ was empty, so I moved the existing js file into it.
- New error! jquery.timeago.js is missing. I didn't see it floating anywhere, so I came back here to investigate.
- I saw this (closed) issue while investigating and switched to 2.12
- Switching to 2.12 from master fixed the showdown.js error, but jquery.timeago.js is still missing.

I'd love to help out, but I don's want to screw up the file structure in the process :)

**Comment by hyances** [comment]
Well, I guess must be reopen then.   I resolve the issue renaming folder and cloning/deploying again.

**Comment by KaiDalgleish** [comment]
I just pulled down a new copy and still get the same errors.

**Comment by hyances** [comment]
Did you follow deployment from https://github.com/hotosm/osm-tasking-manager2#application-deployment ?

**Comment by KaiDalgleish** [comment]
Yes, same errors.

**Comment by hyances** [comment]
And if you clone this way?

git clone --recursive git://github.com/hotosm/osm-tasking-manager2.git
cd osm-tasking-manager2
git checkout tags/2.12.0 -b 2.12

**Comment by KaiDalgleish** [comment]
Success! I had left out the "--recursive", so my clone wasn't getting all the submodules. Thanks for your help :)

**Comment by pgiraud** [comment]
I was about to suggest that "--recursive" is important.
Can you please confirm that it works on 2.13dev (ie. master branch) as well?

**Comment by KaiDalgleish** [comment]
Yes, it's running fine on master branch as well. Thanks for your help!

**Comment by hyances** [comment]
OK, this issue could be considered as closed then.
