### ISSUE TITLE
What's the optimum limit for number of polygons for each project?

### ISSUE THREAD

**Issue by maning** [hotosm/osm-tasking-manager2#751]
I'm dividing a large poly of census blocks into groups for different TM projects.  What's the ballpark limit for number of polys for each project? I noticed that for large TM projects with arbitrary polys, loading the project page become slower.

**Comment by pgiraud** [comment]
You may have more experience than I do.
However, in the V1 of the tasking manager I experienced performances issues with more than 2000 squares. But it's completely different since we were not using arbitrary polygons at that time.

OSMUS may have some experience as well. There's using arbitrary polygons for projects in their instance.
For example http://tasks.openstreetmap.us/project/7.

It shows that not only the number of elements can be a problem. The complexity of each may also be an issue. In the above example, the ".json" file is 4.3MB. Once loaded it works pretty well though (at least on a recent computer).

**Comment by pgiraud** [comment]
@maning did this help? Can we close this issue since it's more a question that a real issue?

**Comment by maning** [comment]
Yes thank you. I reduced my polys to less than 1K.  Closing.
