### ISSUE TITLE
Task manager doesn't tally contributions properly

### ISSUE THREAD

**Issue by dkogan** [hotosm/osm-tasking-manager2#775]
Hi. In the LA building import I'm seeing that the user contribution counts are sometimes incorrect:

https://github.com/osmlab/labuildings/issues/69

That bug report has a potential (and untested patch). If somebody can test and/or apply it, that'd be great.

**Comment by ethan-nelson** [comment]
Well, I guess it depends on the definition of 'contribution count'. Do we put aside whether someone has marked a tile done three times and only count it as one `tile`? Do we count all three times?

I've been under the assumption that the stats were to measure how many times someone has marked a tile done in the project. The numbers don't always add up to the number of tiles either because I believe if two different people mark a tile done that tile will show up in both their counts. (In other words, even with a fix like this, the numbers for all users could still add up to more than the total number of tiles.)

So we should probably decide what we want actually conveyed on the stats page and then possibly clarify the headers a bit as well.

**Comment by dkogan** [comment]
Sure, maybe the code is doing the right thing, but the data is simply
presented in a misleading way.

My only experience here is the instance at

http://labuildingsimport.com/project/2

Look at the Stats tab. I think there's a clear implication that each
user has completed exactly as any tasks as is shown in the list.
Furthermore, here we have a Done %, and I'm willing to bet that it
simply adds up all the Done counts, and looks at the ratio, which would
come out wrong with the current implementation.

I think a unique count would be the more useful thing to report here,
but yall can decide that.

**Comment by ethan-nelson** [comment]
Can you make a pull request on here from your fork?

**Comment by dkogan** [comment]
> Can you make a pull request on here from your fork?

Done:

https://github.com/hotosm/osm-tasking-manager2/pull/776

Please note that this is not at all tested.

**Comment by ethan-nelson** [comment]
No problem! I'll take a look at it soon.

**Comment by ethan-nelson** [comment]
Fixed via #776
