### ISSUE TITLE
required mapping experience

### ISSUE THREAD

**Issue by pgiraud** [hotosm/osm-tasking-manager2#83]
Some projects are appropriate for beginners whereas some are for experienced mappers.
Let's have a field in the database for that.

**Comment by althio** [comment]
@rkiddy 
> On the one hand, is this necessary? You have info in the Instructions which seems pretty clear about this.
> ... having to read the instructions is not a terrible thing, yes?

Read the instructions for a project you undertake for good, yes.
Read 10x instructions just to find a project that matches your skills, no. Big deterrent.

Also, why ask 1000+ persons to read the instructions in detail, only to try to understand what is required, try to guess if they have the skills? Keep in mind it is even harder to find the info when you are not familiar with the structure and style.
Why let 100+ persons fail to guess properly and map without the skill?
Or leave because after reading 5 projects in full they cannot find a project with suitable level?
Required experience and skills could be done, once and for all, by the creator.

**Comment by bgirardot** [comment]
Is this something that could be part of issue #529 the front page redesign, specifically the 2nd example with the list of things to filter projects by?

I totally agree some sort of difficulty rating would help. Even knowing it is "just" buildings doesn't necessarily help as there are places where mapping the buildings is next to impossible and takes someone with experience mapping dense urban areas.

**Comment by althio** [comment]
@bgirardot I agree and I think it is even already partly implemented.

**Comment by bgirardot** [comment]
This could be added and requiring any specific skill level could be optional for the project, but default to no special users.

**Comment by RAytoun** [comment]
I am in agreement for some early indication in description if it is suitable for beginners but I am finding problems arising from the present trend of buildings only and roads only tasks within a project. Certainly we can take into account the difficulty factors such as buildings in slum areas, poor imagery or offset imagery, post disaster comparisons, etc. But by putting a label on it "for beginners" we have less of the more experienced mappers also participating so it becomes pointless to invalidate a square as it is less likely to be corrected. It also means that some errors do not get fixed along the way, by someone who spots an error , and has to wait for validation to be corrected. Some beginners have also 'experimented' with roads on the 'buildings only' tasks which ends up with duplications of roads done on the 'roads only' tasks. I still believe we should be encouraging beginners to do the full range of features so they understand that they need to be mapped in relation to each other. By running a 'buildings only' and a 'roads only' simultaneously means that the more experienced mappers doing roads have their hands tied, they cannot fix any of the buildings errors they come across because they may be duplicating something that is being done on the other task. This separation of easy and difficult tasks because of individual features is not progressing the project or improving the standard of mapping and needs to be rethought.

**Comment by pgiraud** [comment]
Fixed via #954.

**Comment by skalca** [comment]
@pgiraud If this issue is closed, then please closed it. There are over 280 open issues and if some are actually done, they should be closed ASAP.
Thanks :)
