### ISSUE TITLE
Timer resets to 1439 minutes after initial 120 minutes

### ISSUE THREAD

**Issue by briandaviddavidson** [hotosm/osm-tasking-manager2#983]
If you start a cell, then let the timer run down to 0 minutes, the timer will reset to 1439 minutes and doesn't appear to unlock until you physically click the button.

It also seems that if you get out, and then get back into the same cell, the timer moves twice as fast.

See attached gif

![timeissues](https://cloud.githubusercontent.com/assets/2423402/24148859/ee047012-0e16-11e7-9a84-264827842f56.gif)

**Comment by skalca** [comment]
I cannot reproduce this behaviour on the _master_ source code. But I guess it must have something to do with timezones because that 1439 minutes looks a whole like 1440 minutes and that is 8 hours. 
Do you by any chance live on US western coast?
As I can see in the source code (file task.locked.mako) time left is calculated as:

```
time_left = time_locked - current_time + 2 
```

At first everything works OK. Then after 2 hours it falls apart. I presume this: your locked time is later on read as in your time zone instead of UTC+0 as ```current_time is``` is taken in. 

But then again it is only a wild guess. :)

**Comment by skalca** [comment]
1439 looks very close to 1440 minutes which is 24 hours. I believe this behaviour has something to do as how ```locked_time``` is stored in the database. At first it works ok, but then this value is read from database. And there it gets corrupted. Because ```time_left``` gets calculated with help of current time in UTC+0. 

But then again, I cannot reproduce this behaviour from _master_ branch.

**Comment by briandaviddavidson** [comment]
Interesting. So the gif above was reproduced on the [main tasking manager site](http://tasks.hotosm.org/) on [this project](http://tasks.hotosm.org/project/5)

Has this been fixed in master and not deployed to the live version yet?

**Comment by skalca** [comment]
Well, I cannot reproduce it on master, so I guess it works. And also I can see that times are taken in UTC in master so that looks fine.
